sonar.projectKey=hamza-rafik_test-sonar

sonar.sources=.

sonar.token=5940d2ccd64fe2e8ed9d3a530c5e12d0dac6f23f

sonar.sourceEncoding=UTF-8

sonar.java.binaries=bin

sonar.host.url=https://sonarcloud.io

sonar.organization=hamza-rafik
